apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: secrets-store-sync-controller
    app.kubernetes.io/part-of: secrets-store-sync-controller
    app.kubernetes.io/managed-by: kustomize
    secrets-store.io/system: "true"
  name: "metrics-service"
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.metricsPort }}
    protocol: TCP
    targetPort: metrics
  selector:
    control-plane: controller-manager